//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neshanak.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neshanak.App_GlobalResources.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active install.
        /// </summary>
        public static string activeinstall {
            get {
                return ResourceManager.GetString("activeinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adminPanel.
        /// </summary>
        public static string adminPanel {
            get {
                return ResourceManager.GetString("adminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banner management.
        /// </summary>
        public static string bannman {
            get {
                return ResourceManager.GetString("bannman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Blog Post.
        /// </summary>
        public static string blogtext1 {
            get {
                return ResourceManager.GetString("blogtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string blogtext2 {
            get {
                return ResourceManager.GetString("blogtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business code.
        /// </summary>
        public static string buscode {
            get {
                return ResourceManager.GetString("buscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add business.
        /// </summary>
        public static string busiadd {
            get {
                return ResourceManager.GetString("busiadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business list.
        /// </summary>
        public static string busilist {
            get {
                return ResourceManager.GetString("busilist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business managment.
        /// </summary>
        public static string busiman {
            get {
                return ResourceManager.GetString("busiman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business title.
        /// </summary>
        public static string bustitle {
            get {
                return ResourceManager.GetString("bustitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please insert above code.
        /// </summary>
        public static string captchatext {
            get {
                return ResourceManager.GetString("captchatext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main category.
        /// </summary>
        public static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category management.
        /// </summary>
        public static string catnam {
            get {
                return ResourceManager.GetString("catnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change email.
        /// </summary>
        public static string changeEmail {
            get {
                return ResourceManager.GetString("changeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose cat.
        /// </summary>
        public static string chooscat {
            get {
                return ResourceManager.GetString("chooscat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your city.
        /// </summary>
        public static string chooseCity {
            get {
                return ResourceManager.GetString("chooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your country.
        /// </summary>
        public static string chooseCountry {
            get {
                return ResourceManager.GetString("chooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose subcat.
        /// </summary>
        public static string choossubcat {
            get {
                return ResourceManager.GetString("choossubcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column.
        /// </summary>
        public static string col {
            get {
                return ResourceManager.GetString("col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment management.
        /// </summary>
        public static string comman {
            get {
                return ResourceManager.GetString("comman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must consent with terms and conditions.
        /// </summary>
        public static string confirmRuleText {
            get {
                return ResourceManager.GetString("confirmRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose subcat two.
        /// </summary>
        public static string coosesubcattwo {
            get {
                return ResourceManager.GetString("coosesubcattwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string createAddress {
            get {
                return ResourceManager.GetString("createAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string createButt {
            get {
                return ResourceManager.GetString("createButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string createDesc {
            get {
                return ResourceManager.GetString("createDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string createImage {
            get {
                return ResourceManager.GetString("createImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string createLocation {
            get {
                return ResourceManager.GetString("createLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number 1.
        /// </summary>
        public static string createPhone {
            get {
                return ResourceManager.GetString("createPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number 2.
        /// </summary>
        public static string createPhone2 {
            get {
                return ResourceManager.GetString("createPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title .
        /// </summary>
        public static string createTitle {
            get {
                return ResourceManager.GetString("createTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashbaord.
        /// </summary>
        public static string dashbaord {
            get {
                return ResourceManager.GetString("dashbaord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure?.
        /// </summary>
        public static string delbusi {
            get {
                return ResourceManager.GetString("delbusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, .
        /// </summary>
        public static string footeraboutus {
            get {
                return ResourceManager.GetString("footeraboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string footertag {
            get {
                return ResourceManager.GetString("footertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forget your password.
        /// </summary>
        public static string forgetPass {
            get {
                return ResourceManager.GetString("forgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you looking for?.
        /// </summary>
        public static string headerFormInput1 {
            get {
                return ResourceManager.GetString("headerFormInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string headerFormInput2 {
            get {
                return ResourceManager.GetString("headerFormInput2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your country.
        /// </summary>
        public static string headerFormInput3 {
            get {
                return ResourceManager.GetString("headerFormInput3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your city.
        /// </summary>
        public static string headerFormInput4 {
            get {
                return ResourceManager.GetString("headerFormInput4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND THE BEST TO BE.
        /// </summary>
        public static string headertext1 {
            get {
                return ResourceManager.GetString("headertext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find great places to stay, shop,  or visit local experts.
        /// </summary>
        public static string headertext2 {
            get {
                return ResourceManager.GetString("headertext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inactive.
        /// </summary>
        public static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instagram.
        /// </summary>
        public static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last registerd business.
        /// </summary>
        public static string lastbusi {
            get {
                return ResourceManager.GetString("lastbusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string loginEmail {
            get {
                return ResourceManager.GetString("loginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set valid email.
        /// </summary>
        public static string loginEmailError {
            get {
                return ResourceManager.GetString("loginEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password.
        /// </summary>
        public static string loginPass {
            get {
                return ResourceManager.GetString("loginPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please insert password.
        /// </summary>
        public static string loginPassError {
            get {
                return ResourceManager.GetString("loginPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string logosection0 {
            get {
                return ResourceManager.GetString("logosection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In or Register.
        /// </summary>
        public static string logosection1 {
            get {
                return ResourceManager.GetString("logosection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactus.
        /// </summary>
        public static string logosection2 {
            get {
                return ResourceManager.GetString("logosection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string logosection3 {
            get {
                return ResourceManager.GetString("logosection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string logosection4 {
            get {
                return ResourceManager.GetString("logosection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string logosection5 {
            get {
                return ResourceManager.GetString("logosection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no item abvailable.
        /// </summary>
        public static string magnoitem {
            get {
                return ResourceManager.GetString("magnoitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see detail.
        /// </summary>
        public static string magSeedetail {
            get {
                return ResourceManager.GetString("magSeedetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your city.
        /// </summary>
        public static string maincitychoose {
            get {
                return ResourceManager.GetString("maincitychoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere and anytime, We are here to help.
        /// </summary>
        public static string maptext1 {
            get {
                return ResourceManager.GetString("maptext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And we mean that.
        /// </summary>
        public static string maptext2 {
            get {
                return ResourceManager.GetString("maptext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile number 1.
        /// </summary>
        public static string mobile1 {
            get {
                return ResourceManager.GetString("mobile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile number 2.
        /// </summary>
        public static string mobile2 {
            get {
                return ResourceManager.GetString("mobile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news management.
        /// </summary>
        public static string newsman {
            get {
                return ResourceManager.GetString("newsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no item found.
        /// </summary>
        public static string noItemFound {
            get {
                return ResourceManager.GetString("noItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special offer.
        /// </summary>
        public static string offer {
            get {
                return ResourceManager.GetString("offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page mangement.
        /// </summary>
        public static string pageman {
            get {
                return ResourceManager.GetString("pageman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular in all categories.
        /// </summary>
        public static string popularText1 {
            get {
                return ResourceManager.GetString("popularText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string popularText2 {
            get {
                return ResourceManager.GetString("popularText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Suggestion.
        /// </summary>
        public static string randomtext1 {
            get {
                return ResourceManager.GetString("randomtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string randomtext2 {
            get {
                return ResourceManager.GetString("randomtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent View.
        /// </summary>
        public static string recenttext1 {
            get {
                return ResourceManager.GetString("recenttext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string recenttext2 {
            get {
                return ResourceManager.GetString("recenttext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered business.
        /// </summary>
        public static string registerdbusi {
            get {
                return ResourceManager.GetString("registerdbusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered user.
        /// </summary>
        public static string registerduser {
            get {
                return ResourceManager.GetString("registerduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your email.
        /// </summary>
        public static string registerEmail {
            get {
                return ResourceManager.GetString("registerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please insert correct email.
        /// </summary>
        public static string registerEmailError {
            get {
                return ResourceManager.GetString("registerEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your name.
        /// </summary>
        public static string registerName {
            get {
                return ResourceManager.GetString("registerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name must be inserted.
        /// </summary>
        public static string registerNameError {
            get {
                return ResourceManager.GetString("registerNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert new password.
        /// </summary>
        public static string registerPassword {
            get {
                return ResourceManager.GetString("registerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password lengh must be 6 at least.
        /// </summary>
        public static string registerPasswordError {
            get {
                return ResourceManager.GetString("registerPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat password.
        /// </summary>
        public static string registerPasswordRepeat {
            get {
                return ResourceManager.GetString("registerPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password must be identical.
        /// </summary>
        public static string registerPasswordRepeatError {
            get {
                return ResourceManager.GetString("registerPasswordRepeatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your phone.
        /// </summary>
        public static string registerPhone {
            get {
                return ResourceManager.GetString("registerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone must be inserted.
        /// </summary>
        public static string registerPhoneError {
            get {
                return ResourceManager.GetString("registerPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string rememberme {
            get {
                return ResourceManager.GetString("rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resend code.
        /// </summary>
        public static string resendCode {
            get {
                return ResourceManager.GetString("resendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slider management.
        /// </summary>
        public static string slideman {
            get {
                return ResourceManager.GetString("slideman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub category.
        /// </summary>
        public static string subcat {
            get {
                return ResourceManager.GetString("subcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub category two.
        /// </summary>
        public static string subcat2 {
            get {
                return ResourceManager.GetString("subcat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telegram.
        /// </summary>
        public static string telegram {
            get {
                return ResourceManager.GetString("telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user management.
        /// </summary>
        public static string userman {
            get {
                return ResourceManager.GetString("userman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert verification code.
        /// </summary>
        public static string verifyCode {
            get {
                return ResourceManager.GetString("verifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, ligula quam maximus diam, fringilla aliquet leo est ut lorem. Donec sit amet feugiat neque. Phasellus quis felis in magna elementum dapibus at nec dui. Nulla ut velit eu neque pulvinar pulvinar quis in orci. Vestibulum ni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string viewProductContent1 {
            get {
                return ResourceManager.GetString("viewProductContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, ligula quam maximus diam, fringilla aliquet leo est ut lorem. Donec sit amet feugiat neque. Phasellus quis felis in magna elementum dapibus at nec dui. Nulla ut velit eu neque pulvinar pulvinar quis in orci. Vestibulum ni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string viewProductContent2 {
            get {
                return ResourceManager.GetString("viewProductContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, ligula quam maximus diam, fringilla aliquet leo est ut lorem. Donec sit amet feugiat neque. Phasellus quis felis in magna elementum dapibus at nec dui. Nulla ut velit eu neque pulvinar pulvinar quis in orci. Vestibulum ni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string viewProductContent3 {
            get {
                return ResourceManager.GetString("viewProductContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Time.
        /// </summary>
        public static string viewProductHeader1 {
            get {
                return ResourceManager.GetString("viewProductHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Over The Team.
        /// </summary>
        public static string viewProductHeader2 {
            get {
                return ResourceManager.GetString("viewProductHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Features.
        /// </summary>
        public static string viewProductHeader3 {
            get {
                return ResourceManager.GetString("viewProductHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere and anytime, We are here to help .
        /// </summary>
        public static string viewProductText1 {
            get {
                return ResourceManager.GetString("viewProductText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And we mean that.
        /// </summary>
        public static string viewProductText2 {
            get {
                return ResourceManager.GetString("viewProductText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wellcome.
        /// </summary>
        public static string wellcome {
            get {
                return ResourceManager.GetString("wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whatsapp.
        /// </summary>
        public static string whatsapp {
            get {
                return ResourceManager.GetString("whatsapp", resourceCulture);
            }
        }
    }
}
