//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neshanak.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neshanak.App_GlobalResources.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Blog Post.
        /// </summary>
        public static string blogtext1 {
            get {
                return ResourceManager.GetString("blogtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string blogtext2 {
            get {
                return ResourceManager.GetString("blogtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, .
        /// </summary>
        public static string footeraboutus {
            get {
                return ResourceManager.GetString("footeraboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string footertag {
            get {
                return ResourceManager.GetString("footertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you looking for?.
        /// </summary>
        public static string headerFormInput1 {
            get {
                return ResourceManager.GetString("headerFormInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string headerFormInput2 {
            get {
                return ResourceManager.GetString("headerFormInput2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your country.
        /// </summary>
        public static string headerFormInput3 {
            get {
                return ResourceManager.GetString("headerFormInput3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your city.
        /// </summary>
        public static string headerFormInput4 {
            get {
                return ResourceManager.GetString("headerFormInput4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND THE BEST TO BE.
        /// </summary>
        public static string headertext1 {
            get {
                return ResourceManager.GetString("headertext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find great places to stay, shop,  or visit local experts.
        /// </summary>
        public static string headertext2 {
            get {
                return ResourceManager.GetString("headertext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In or Register.
        /// </summary>
        public static string logosection1 {
            get {
                return ResourceManager.GetString("logosection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactus.
        /// </summary>
        public static string logosection2 {
            get {
                return ResourceManager.GetString("logosection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string logosection3 {
            get {
                return ResourceManager.GetString("logosection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular in all categories.
        /// </summary>
        public static string popularText1 {
            get {
                return ResourceManager.GetString("popularText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string popularText2 {
            get {
                return ResourceManager.GetString("popularText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Suggestion.
        /// </summary>
        public static string randomtext1 {
            get {
                return ResourceManager.GetString("randomtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string randomtext2 {
            get {
                return ResourceManager.GetString("randomtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent View.
        /// </summary>
        public static string recenttext1 {
            get {
                return ResourceManager.GetString("recenttext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are some of uss anyway.
        /// </summary>
        public static string recenttext2 {
            get {
                return ResourceManager.GetString("recenttext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, ligula quam maximus diam, fringilla aliquet leo est ut lorem. Donec sit amet feugiat neque. Phasellus quis felis in magna elementum dapibus at nec dui. Nulla ut velit eu neque pulvinar pulvinar quis in orci. Vestibulum ni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string viewProductContent1 {
            get {
                return ResourceManager.GetString("viewProductContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, ligula quam maximus diam, fringilla aliquet leo est ut lorem. Donec sit amet feugiat neque. Phasellus quis felis in magna elementum dapibus at nec dui. Nulla ut velit eu neque pulvinar pulvinar quis in orci. Vestibulum ni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string viewProductContent2 {
            get {
                return ResourceManager.GetString("viewProductContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a lectus finibus, sagittis lorem vitae, pulvinar metus. Etiam placerat orci mauris, nec aliquet augue vulputate vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis, risus eget volutpat vestibulum, ligula quam maximus diam, fringilla aliquet leo est ut lorem. Donec sit amet feugiat neque. Phasellus quis felis in magna elementum dapibus at nec dui. Nulla ut velit eu neque pulvinar pulvinar quis in orci. Vestibulum ni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string viewProductContent3 {
            get {
                return ResourceManager.GetString("viewProductContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Time.
        /// </summary>
        public static string viewProductHeader1 {
            get {
                return ResourceManager.GetString("viewProductHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Over The Team.
        /// </summary>
        public static string viewProductHeader2 {
            get {
                return ResourceManager.GetString("viewProductHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Features.
        /// </summary>
        public static string viewProductHeader3 {
            get {
                return ResourceManager.GetString("viewProductHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere and anytime, We are here to help .
        /// </summary>
        public static string viewProductText1 {
            get {
                return ResourceManager.GetString("viewProductText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And we mean that.
        /// </summary>
        public static string viewProductText2 {
            get {
                return ResourceManager.GetString("viewProductText2", resourceCulture);
            }
        }
    }
}
